### PR TITLE
fix($hmr): Target correct link tags when hot reloading.

### LINKED ISSUE #23: New styles overridden in DOM after hot update.
👋 I've been working on bootstrapping a new repo with your new universal family and running into some trouble with CSS hot reloading. Hot updates are applied, but they appear earlier in the cascade than the original styles and are consequently overridden by the CSS they're meant to replace. Here, I've changed the `h1`'s color from red to blue; you can see that the new style is loaded, but not applied:

screen shot 1

Just curious whether you'd seen anything like this before. If it helps, there's a small amount of code at <https://github.com/ignota/ignota2> that shows what I _think_ should work. (Frustratingly, it's largely pulled from another repo where CSS HMR _is_ working, and I can't account for the difference. 😡 )

Thanks in advance for any thoughts you might have!

### PR DESCRIPTION
**Pull request by phyllisstein**
Update the logic for comparing link tags' URLs so that the correct pathname is matched against.

Fixes #23.

### CODE REVIEW

**Comment by phyllisstein** [comment]
And here she is in action:

screenflow

**Comment by faceyspacey** [comment]
Excellent! Question: what's the browser support for `URL`? I've actually never used that.

Also, does this solve this issue:

**Comment by phyllisstein** [comment]
Fair question! Looks like support is solid except in IE: <http://caniuse.com/#feat=url>. For what it's worth I can't get HMR working _at all_ in IE---`webpack-hot-middleware` throws errors about a missing `EventSource` object---so I'd argue that it's up for grabs how much time and energy should go into supporting it (especially when there's [a `URL` polyfill](https://github.com/github/url-polyfill) extant).

As written this will not fix #25, but if you want to go the URL route it's a pretty quick fix---just have to add the base URL as the constructor's second argument. I'll take a look at it this afternoon.

File: hotModuleReplacement.js [hunk 1]
```diff
@@ -1,18 +1,16 @@
 module.exports = function(publicPath, outputFilename) {
   if (document) {
-    var origin = document.location.protocol + '//' + document.location.hostname + (document.location.port ? ':' + document.location.port: '');
-    var newHref = origin + publicPath + outputFilename
-    var styleSheets = document.getElementsByTagName('link');
+    var newHref = publicPath.match(/https?:/g) ? new URL(outputFilename, publicPath) : new URL(outputFilename, window.location);
```
Comment (lutzk) [inline hotModuleReplacement.js]: is the publicPath lost in case it is relative?
new URL(outputFilename, window.location); => new URL(publicPath + outputFilename, window.location); ?

Comment (phyllisstein) [inline hotModuleReplacement.js]: Good catch! Wasn't necessary with my setup because `publicPath` was `/`, but I think you're right that if it's more involved it'd be dropped on the floor. Fix coming presently, thanks!

**Comment by faceyspacey** [comment]
I like the URL route. As you mentioned, webpack-hot-middleware has issues with IE anyway, and polyfills are available:

https://github.com/glenjamin/webpack-hot-middleware/issues/11
https://github.com/glenjamin/webpack-hot-middleware#use-on-browsers-without-eventsource
https://libraries.io/search?platforms=NPM&q=eventsource+polyfill

Otherwise, excellent work! Thanks for this.

**Comment by phyllisstein** [comment]
De nada! Glad to give back. 💖
